/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_Turing;

/**
 *
 * @author Kyrion
 */
public final class VTuring extends javax.swing.JFrame {

    /**
     * Creates new form VPCopy
     */


    public VTuring() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnMainPanel = new javax.swing.JPanel();
        jSPnComputos = new javax.swing.JScrollPane();
        txComputos = new javax.swing.JTextArea();
        jSPnTupla = new javax.swing.JScrollPane();
        txTupla = new javax.swing.JTextArea();
        jTitulo = new javax.swing.JLabel();
        txCadenaEntrada = new javax.swing.JTextField();
        jCadenaEntrada = new javax.swing.JLabel();
        jbComputar = new javax.swing.JButton();
        jTupla = new javax.swing.JLabel();
        jComputos = new javax.swing.JLabel();
        jbCargar = new javax.swing.JButton();
        jCadenaModificada = new javax.swing.JLabel();
        txCadenaModificada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnMainPanel.setBackground(new java.awt.Color(255, 204, 51));

        txComputos.setEditable(false);
        txComputos.setColumns(20);
        txComputos.setRows(5);
        jSPnComputos.setViewportView(txComputos);

        txTupla.setEditable(false);
        txTupla.setColumns(20);
        txTupla.setRows(5);
        jSPnTupla.setViewportView(txTupla);

        jTitulo.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jTitulo.setText("MÁQUINA DE TURING");

        jCadenaEntrada.setText("Cadena de entrada");

        jbComputar.setText("COMPUTAR");
        jbComputar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComputarActionPerformed(evt);
            }
        });

        jTupla.setText("Tupla");

        jComputos.setText("Cómputos");

        jbCargar.setText("CARGAR");

        jCadenaModificada.setText("Cadena modificada");

        javax.swing.GroupLayout jPnMainPanelLayout = new javax.swing.GroupLayout(jPnMainPanel);
        jPnMainPanel.setLayout(jPnMainPanelLayout);
        jPnMainPanelLayout.setHorizontalGroup(
            jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMainPanelLayout.createSequentialGroup()
                .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnMainPanelLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jTupla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPnMainPanelLayout.createSequentialGroup()
                        .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnMainPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jSPnTupla, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnMainPanelLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jbCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnMainPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jSPnComputos, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMainPanelLayout.createSequentialGroup()
                        .addComponent(jbComputar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMainPanelLayout.createSequentialGroup()
                        .addComponent(jComputos)
                        .addGap(186, 186, 186))))
            .addGroup(jPnMainPanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCadenaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCadenaModificada))
                .addGap(18, 18, 18)
                .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txCadenaEntrada)
                    .addComponent(txCadenaModificada, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTitulo)
                .addGap(150, 150, 150))
        );
        jPnMainPanelLayout.setVerticalGroup(
            jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCadenaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCadenaEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCadenaModificada)
                    .addComponent(txCadenaModificada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTupla)
                    .addComponent(jComputos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPnTupla, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSPnComputos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbComputar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbComputarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComputarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbComputarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VTuring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VTuring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VTuring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VTuring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VTuring().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCadenaEntrada;
    private javax.swing.JLabel jCadenaModificada;
    private javax.swing.JLabel jComputos;
    public javax.swing.JPanel jPnMainPanel;
    private javax.swing.JScrollPane jSPnComputos;
    private javax.swing.JScrollPane jSPnTupla;
    public javax.swing.JLabel jTitulo;
    private javax.swing.JLabel jTupla;
    public javax.swing.JButton jbCargar;
    public javax.swing.JButton jbComputar;
    public javax.swing.JTextField txCadenaEntrada;
    public javax.swing.JTextField txCadenaModificada;
    public javax.swing.JTextArea txComputos;
    public javax.swing.JTextArea txTupla;
    // End of variables declaration//GEN-END:variables
}
